### ISSUE TITLE
yara-ttd tool got stuck

### ISSUE THREAD

**Issue by ppxiaoxiao** [airbus-cert/yara-ttd#5]
![image](https://github.com/airbus-cert/yara-ttd/assets/37894461/6ad75bf4-83ee-43da-9513-b86645ff46a4)

I used the test file in the git repository and tried to run the command `".\yara-ttd -m 2 sig\rules.yar test_upx01.run"`, but it got stuck. What could be the reason?

**Comment by atxr** [comment]
Hi @ppxiaoxiao thanks for raising this issue!

Actually, yara-ttd isn't stuck, it's scanning the whole memory (mode 2)
But as mentioned in the README, this can take a very long time.
That's why I implemented memory optimizations that allow you to select which part of the memory you want to scan.
I would advise you to use mode 1, ie memory of loaded modules + heap
If you prefer a fast scan rather than a precise scan, you can also ignore the heap and use mode 0 (default mode)

Don't hesitate to check the [README regarding memory modes](https://github.com/airbus-cert/yara-ttd#memory-modes).
